In [1]:
import pandas as pd
import pickle
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
dataset=pd.read_csv("50_Startups.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]

In [5]:
dependent=dataset[['Profit']]

In [6]:
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [7]:
# Load trained SVR model
with open("finalized_model_svr_preprocessed.sav", "rb") as model_file:
    loaded_model = pickle.load(model_file)

# Load scalers
with open("scaler_x.pkl", "rb") as scaler_x_file:
    scaler_x = pickle.load(scaler_x_file)

with open("scaler_y.pkl", "rb") as scaler_y_file:
    scaler_y = pickle.load(scaler_y_file)

In [8]:
preinput=scaler_x.transform([[13000,12000,4000,0,1]])

C:\Users\Mellinaa Sanjeevi\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [9]:
preinput

array([[-1.22774637, -4.33835385, -1.50744257, -0.5       ,  1.30088727]])

In [10]:
loaded_model=pickle.load(open("finalized_model_svr_preprocessed.sav",'rb'))
result=loaded_model.predict(preinput)

In [11]:
result

array([-1.01154876])

In [12]:
preoutput=scaler_y.inverse_transform([result])

In [13]:
preoutput

array([[66715.81485064]])